"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 07:41:57.638166
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_usage_at'), ['at'], unique=False)

    op.create_table('connector_status',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.String(length=512), nullable=False),
    sa.Column('last_ok_at', sa.DateTime(), nullable=True),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_beat_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('negotiable', sa.Boolean(), nullable=False),
    sa.Column('delivery', sa.String(length=16), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('storage_gb', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('battery_health', sa.Integer(), nullable=True),
    sa.Column('battery_cycles', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('sim_type', sa.String(length=32), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('travel_minutes', sa.Float(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('location_confidence', sa.String(length=8), nullable=False),
    sa.Column('seller_id', sa.String(length=128), nullable=True),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('seller_account_age_days', sa.Integer(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('image_hashes', sa.JSON(), nullable=False),
    sa.Column('raw_data_reference', sa.String(length=256), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('candidate_key', sa.String(length=128), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=True),
    sa.Column('deal_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=8), nullable=True),
    sa.Column('my_max_buy', sa.Float(), nullable=True),
    sa.Column('expected_sale', sa.Float(), nullable=True),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('roi_percent', sa.Float(), nullable=True),
    sa.Column('evaluation', sa.JSON(), nullable=False),
    sa.Column('alerted_price', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_candidate_key'), ['candidate_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_marketplace'), ['marketplace'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_tier'), ['tier'], unique=False)

    op.create_table('locality_travel',
    sa.Column('locality', sa.String(length=128), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=False),
    sa.Column('km', sa.Float(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('locality')
    )
    op.create_table('market_comparable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('condition_band', sa.String(length=16), nullable=False),
    sa.Column('battery_band', sa.String(length=8), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('marketplace', sa.String(length=32), nullable=True),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_comparable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_comparable_model'), ['model'], unique=False)

    op.create_table('price_rule_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('source_name', sa.String(length=256), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_sample', sa.Boolean(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_event_at'), ['at'], unique=False)

    op.create_table('inventory_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('battery_health', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('purchase_path', sa.String(length=16), nullable=False),
    sa.Column('purchase_cost', sa.Float(), nullable=True),
    sa.Column('repair_cost', sa.Float(), nullable=False),
    sa.Column('predicted_sale', sa.Float(), nullable=True),
    sa.Column('predicted_profit', sa.Float(), nullable=True),
    sa.Column('predicted_score', sa.Float(), nullable=True),
    sa.Column('listing_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_platform', sa.String(length=32), nullable=True),
    sa.Column('fees_paid', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('return_window_ends_at', sa.DateTime(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=False),
    sa.Column('is_paper', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_item_status'), ['status'], unique=False)

    op.create_table('listing_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_snapshot_listing_id'), ['listing_id'], unique=False)

    op.create_table('listing_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('primary_listing_id', sa.Integer(), nullable=False),
    sa.Column('linked_listing_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['linked_listing_id'], ['listing.id'], ),
    sa.ForeignKeyConstraint(['primary_listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing_source', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_source_primary_listing_id'), ['primary_listing_id'], unique=False)

    op.create_table('price_rule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('max_buy_price', sa.Float(), nullable=False),
    sa.Column('min_battery_health', sa.Integer(), nullable=True),
    sa.Column('condition_rules', sa.String(length=256), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['version_id'], ['price_rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_rule_model'), ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_rule_version_id'), ['version_id'], unique=False)

    op.create_table('telegram_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=False),
    sa.Column('queued_for_quiet_hours', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('path', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory_item.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=48), nullable=False),
    sa.Column('label', sa.String(length=256), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inspection_item_inspection_id'), ['inspection_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inspection_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inspection_item_inspection_id'))

    op.drop_table('inspection_item')
    op.drop_table('inspection')
    op.drop_table('telegram_notification')
    with op.batch_alter_table('price_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_rule_version_id'))
        batch_op.drop_index(batch_op.f('ix_price_rule_model'))

    op.drop_table('price_rule')
    with op.batch_alter_table('listing_source', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_source_primary_listing_id'))

    op.drop_table('listing_source')
    with op.batch_alter_table('listing_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_snapshot_listing_id'))

    op.drop_table('listing_snapshot')
    with op.batch_alter_table('inventory_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_item_status'))

    op.drop_table('inventory_item')
    with op.batch_alter_table('system_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_event_at'))

    op.drop_table('system_event')
    op.drop_table('price_rule_version')
    with op.batch_alter_table('market_comparable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_comparable_model'))

    op.drop_table('market_comparable')
    op.drop_table('locality_travel')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_tier'))
        batch_op.drop_index(batch_op.f('ix_listing_model'))
        batch_op.drop_index(batch_op.f('ix_listing_marketplace'))
        batch_op.drop_index(batch_op.f('ix_listing_external_id'))
        batch_op.drop_index(batch_op.f('ix_listing_content_hash'))
        batch_op.drop_index(batch_op.f('ix_listing_candidate_key'))

    op.drop_table('listing')
    op.drop_table('heartbeat')
    op.drop_table('connector_status')
    with op.batch_alter_table('ai_usage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_usage_at'))

    op.drop_table('ai_usage')
    # ### end Alembic commands ###
